# Generated by Django 2.2.13 on 2021-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(default='C:\\Users\\klim1\\Projects\\WebShop\\templates\\img\\image_not_found.png', upload_to=''),
        ),
    ]
