# Generated by Django 2.2.13 on 2021-04-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_item_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='images',
            new_name='image',
        ),
    ]
